### PR TITLE
WIP: Handle mutex patch from gsamfira.

### PR DESCRIPTION
**Pull request by cmars**

### CODE REVIEW

**Comment by cmars** [comment]
Ran cmd/jujud/agent tests 300 times with this patch: https://gist.github.com/anonymous/11d575817b068f20c994816ed332b5c4

**Comment by cmars** [comment]
Without this patch: https://gist.github.com/anonymous/37c739b824809093a97e84bd3d1d3fb3

**Comment by natefinch** [comment]
This is not really landable as-is... even the basic premise gives me the willies... a package-global lock?  That's just asking for trouble.   I'll try to nail down a better fix for this, even if it's just a timeout and/or a "don't do that".

**Comment by natefinch** [comment]
This is fixed by #21

**Pull request closed without merging**
