### PR TITLE
fix: AcceptPipe CloseHandle param is nil panic error

### PR DESCRIPTION
**Pull request by xlango**
Resolve the panic issue where executing Close during AcceptPipe listening causes the HEvent parameter of CloseHandle to be 0

### CODE REVIEW

**Comment by xlango** [comment]
Please merge and publish the release version@natefinch

**Comment by xlango** [comment]
to https://github.com/xlango/npipe

**Comment by xlango** [comment]
to https://github.com/xlango/npipe

**Comment by natefinch** [comment]
@xlango definitely happy to have you take over this. I don't have a use for this code anymore, nor a windows machine to test it on, so I'm happy someone else is looking at it.

**Pull request closed without merging**
